### ISSUE TITLE
Fix the Sign Up Fields (IMPORTANT)

### ISSUE THREAD

**Issue by tiffanywilliams** [rndvouz/rndvouz_mobile_app#82]
Users cannot sign up for an account because they are unable to type in the sign-up fields. Problem only appears to be affecting the sign-up page. Profile setup (after registering your email, username, and password) works okay. All the other text fields work okay.

**Comment by tiffanywilliams** [comment]
Users cannot sign up for an account because they are unable to type in the sign-up fields. Problem only appears to be affecting the sign-up page. Profile setup (after registering your email, username, and password) works okay. All the other text fields work okay.

**Comment by jeff-yc-wong** [comment]
Hot fix in main
